package lexicalanalyzer;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Test {
	 /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String[] args) throws FileNotFoundException {        
        //Take code input from file
    	Scanner reader = new Scanner(new File("C:\\Users\\matth\\eclipse-workspace\\COMP 360_P1\\src\\input.txt\\"));
        ArrayList<String> lines = new ArrayList<>();

        System.out.println("The Lexemes: ");
        //Reads every line and then splits everything into lexemes
        while (reader.hasNextLine()) {
            String str = reader.nextLine(); //Reads the lines
            if (!(str.length() == 0)) {     //If no blank lines detected, then continue
            	//String[] strSplit = str.trim().split("\\s+|\\s*,\\s*|\\;+|\\\"+|\\:+|\\[+|\\]+");
            	String[] strSplit = str.trim().split("\\s+|(?=[(){};])|(?<=[(){};])");
   
            	
            	//Add the Container List to the ArrayList 
            	for (String lexemes: strSplit) {
                    if (!lexemes.isEmpty() && !lexemes.matches("\\s*")) {
            		System.out.println("The Next Lexeme is: " + lexemes);
            		
            	}
            }
        }
        }
  
System.out.println("The Tokens: ");

    String inputFilePath = "C:\\Users\\matth\\eclipse-workspace\\COMP 360_P1\\src\\input.txt\\";

    // Parse the input file
    boolean isValid = parseInput(inputFilePath);

    // Print the result
    if (isValid) {
        System.out.println("The test program is generated by the EBNF grammar for Simple Function");
    } else {
        System.out.println("The test program cannot be generated by the EBNF Grammar for Simple Function.");
        System.out.println("The first syntax error is");
    }
 }
    //END OF MAIN
    // PARSER
    private static boolean parseInput(String filePath) {
    try {
        Scanner scanner = new Scanner(new File(filePath));
        scanner.useDelimiter("\\s+|(?=[(){};])|(?<=[(){};])");
        // Parse the program according to the grammar
        if (parseProgram(scanner)) {
            // If the entire program is parsed successfully, return true
            return true;
        } else {
            // If there are syntax errors in the program, return false
            return false;
        }
    } catch (FileNotFoundException e) {
        System.err.println("File not found: " + filePath);
        return false;
    }
}

    private static boolean parseProgram(Scanner scanner) {
    // Check if the next token matches the start symbol "<program>"
    if (scanner.hasNext("void")) {
        System.out.println("Found <keyword>");
        scanner.next(); // Consume the keyword token
        return parseIdent(scanner) && scanner.next().equals("(") && scanner.next().equals(")") &&
                scanner.next().equals("{") && parseDeclares(scanner) && parseLoop(scanner) &&
                scanner.next().equals(")") && parseAssignment(scanner) && scanner.next().equals("}");
    } else {
        return false;
    }
}

    private static boolean parseDeclares(Scanner scanner) {
    // Check if the next token matches the non-terminal "<declares>"
    if (scanner.hasNext("int")) {
        System.out.println("Found <keyword>");
        scanner.next(); // Consume the keyword token
        return parseIdent(scanner) && scanner.next().equals("=") && parseConst(scanner) &&
                scanner.next().equals(";");
    } else {
        System.out.println("Expected <keyword>");
        return false;
    }
}

    private static boolean parseLoop(Scanner scanner) {
    // Check if the next token matches the non-terminal "<loop>"
    if (scanner.hasNext("while")) {
        System.out.println("Found <keyword>");
        scanner.next(); // Consume the "while" keyword token
        
        // Check if the next token is "("
        String nextToken = scanner.next();
        if (nextToken.equals("(")) {
            // Consume the "(" token
            // Check if the next tokens are a valid identifier followed by ">=" tokens
            if (parseIdent(scanner)) {
                String lessthan = scanner.next();
                //System.out.print(less than);
                if (lessthan.equals(">=") && parseConst(scanner)) {
                	System.out.println("Found <loop>");
                	return true;
                }
                else {
                	System.out.print("Expected <loop>");
                }
                }
                // {
                 //   System.out.println(nextToken2);
                    // Consume the ">=" token and continue parsing...
               //     return ;
                }
            }
    //System.out.print("false");
    return false;
    
} 

    private static boolean parseAssignment(Scanner scanner) {
    // Check if the next token matches the non-terminal "<assignment>"
    if (scanner.hasNext("[a-z]")) {
        System.out.println("Found <ident>");
        scanner.next(); // Consume the identifier token
        return scanner.next().equals("=") && parseIdent(scanner) &&
                scanner.next().equals("-") && parseConst(scanner) &&
                scanner.next().equals(";");
    } else {
        System.out.println("Expected <ident>");
        return false;
    }
}

    private static boolean parseIdent(Scanner scanner) {
    // Check if the next token matches the non-terminal "<ident>"
	if (scanner.hasNext("[a-zA-Z0-9]+")){
        System.out.println("Found <keyword>");
        scanner.next(); // Consume the identifier token
        return true;
    } else {
        System.out.println("Expected <keyword>");
        return false;
    }
}

    private static boolean parseConst(Scanner scanner) {
    // Check if the next token matches the non-terminal "<const>"
    if (scanner.hasNextInt()) {
        System.out.println("Found <const>");
        scanner.nextInt(); // Consume the integer token
        return true;
    } else {
        System.out.println("Expected <const>");
        return false;
    }
}
}

